version: '2'
services:
  mysqlmaster:
    build: ./cnf/master/.
    hostname: mysqlmaster
    container_name: mysqlmaster
    environment:
      - MYSQL_NODE_ROLE=MASTER
      - MYSQL_SERVER_ID=1
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    ports:
      - "3309:3306"
    command: "mysqld --server-id=1"
    depends_on:
      - mysqlslave
  mysqlslave:
    build: ./cnf/slave/.
    hostname: mysqlslave
    container_name: mysqlslave
    ports:
      - "3310:3306"
    environment:
      - MYSQL_NODE_ROLE=SLAVE
      - MYSQL_SERVER_ID=2
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=% #links
    command: "mysqld --server-id=2"
  mysqlconfigure:
    build: ./cnf/master/.
    container_name: mysqlCnf
    depends_on:
      - mysqlmaster
      - mysqlslave
    environment:
      - MYSQL_NODE_ROLE=CONNECT
      - MYSQL_SLAVE_PASSWORD=root
      - MYSQL_MASTER_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_REPLICATION_USER=repl
      - MYSQL_REPLICATION_PASSWORD=repl
      - MYSQL_ROOT_HOST=%
    command: /bin/bash -x /mysql_connector.sh
  nginx:
    build: ./cnf/nginx/.
    hostname: "nginx"
    container_name: "nginx"
    depends_on:
      - mysqlmaster
      - mysqlslave
    ports:
      - 3306:3306
