version: '2'
services:
  mysqlmaster:
    image: mysql/mysql-server:5.7.23
    container_name: mysqlMaster
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3309:3306"
    volumes:
      - ./cnf/master:/etc/mysql/conf.d/
  mysqlslave:
    image: mysql/mysql-server:5.7.23
    container_name: mysqlDublicate
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./cnf/slave:/etc/mysql/conf.d/
  mysqlconfigure:
    image: mysql/mysql-server:5.7.23
    container_name: mysqlCnf
    environment:
      - "MYSQL_SLAVE_PASSWORD=root"
      - "MYSQL_MASTER_PASSWORD=root"
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_REPLICATION_USER=repl"
      - "MYSQL_REPLICATION_PASSWORD=repl"
    volumes:
      - ./cnf/mysql_connector.sh:/tmp/mysql_connector.sh
    command: /bin/bash -x /tmp/mysql_connector.sh
